import { Product, Order } from "./types";

// ── Full Product Catalogue ──
export const products: Product[] = [
  {
    id: "gg-001",
    name: "Celestial Silver Photo Frame",
    slug: "celestial-silver-photo-frame",
    category: "Home Decor",
    categorySlug: "home-decor",
    brand: "GiftGenius Originals",
    description:
      "Handcrafted sterling silver photo frame with celestial engravings. Each piece is individually polished by artisans in Jaipur. The perfect keepsake for cherished memories — ideal for weddings, anniversaries, and housewarmings.",
    price: 2499,
    basePrice: 3499,
    discount: 29,
    rating: 4.8,
    reviews: 2847,
    image: "/products/frame.png",
    images: ["/products/frame.png"],
    ar: true,
    badge: "Trending in Mumbai",
    stock: 4,
    sku: "GG-001-SILV-FRM",
    colors: [
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Gold", hex: "#FFD700" },
      { name: "Rose Gold", hex: "#B76E79" },
    ],
    sizes: ["6×8", "8×10", "10×12"],
    tags: ["wedding", "anniversary", "housewarming", "photo"],
    specifications: {
      Material: "Sterling Silver 925",
      Weight: "340g",
      Dimensions: "8×10 inches",
      Finish: "Mirror Polish",
      Origin: "Jaipur, Rajasthan",
    },
    careInstructions: "Wipe with a soft dry cloth. Avoid contact with water or chemicals. Store in the provided velvet pouch.",
  },
  {
    id: "gg-002",
    name: "Designer Rakhi Gift Set",
    slug: "designer-rakhi-gift-set",
    category: "Festival",
    categorySlug: "festival",
    brand: "GiftGenius Festive",
    description:
      "Premium rakhi set featuring hand-tied silk threads with Swarovski crystal accents. Comes with artisan sweets, kumkum-chawal, and a personalised greeting card. Express the bond of sibling love.",
    price: 799,
    basePrice: 1299,
    discount: 38,
    rating: 4.6,
    reviews: 1203,
    image: "/products/rakhi.png",
    images: ["/products/rakhi.png"],
    ar: false,
    badge: "Festival Pick",
    stock: 52,
    sku: "GG-002-RKHI-SET",
    colors: [
      { name: "Red & Gold", hex: "#DC2626" },
      { name: "Purple & Silver", hex: "#7C3AED" },
    ],
    sizes: ["Standard"],
    tags: ["raksha-bandhan", "festival", "sibling", "traditional"],
    specifications: {
      Contents: "2 Rakhis, Sweets Box, Kumkum-Chawal, Card",
      Material: "Silk Thread, Swarovski Crystal",
      "Shelf Life": "Sweets: 15 days",
      Packaging: "Premium Gift Box",
    },
    careInstructions: "Consume sweets within 15 days. Store rakhi away from moisture.",
  },
  {
    id: "gg-003",
    name: "Crystal Aurora Lamp",
    slug: "crystal-aurora-lamp",
    category: "Lighting",
    categorySlug: "lighting",
    brand: "Lumière Studio",
    description:
      "A mesmerising colour-changing crystal lamp inspired by the Northern Lights. 16 RGB modes with touch control and remote. USB-C rechargeable with 12-hour battery life. The perfect ambient gift for any room.",
    price: 1899,
    basePrice: 2599,
    discount: 27,
    rating: 4.9,
    reviews: 3421,
    image: "/products/lamp.png",
    images: ["/products/lamp.png"],
    ar: true,
    badge: "Best Seller",
    stock: 18,
    sku: "GG-003-CRYS-LMP",
    colors: [
      { name: "Clear Crystal", hex: "#E0E7FF" },
      { name: "Smoky", hex: "#6B7280" },
    ],
    sizes: ["Small (15cm)", "Large (25cm)"],
    tags: ["home-decor", "lighting", "birthday", "diwali"],
    specifications: {
      Material: "K9 Crystal Glass",
      Modes: "16 RGB Colours",
      Battery: "3000mAh (12 hours)",
      Charging: "USB-C",
      Height: "15cm / 25cm",
    },
    careInstructions: "Clean with microfiber cloth. Do not submerge in water.",
  },
  {
    id: "gg-004",
    name: "Personalised Name Mug",
    slug: "personalised-name-mug",
    category: "Personalized",
    categorySlug: "personalized",
    brand: "GiftGenius Custom",
    description:
      "Premium ceramic mug with your custom name or message in elegant calligraphy. Microwave & dishwasher safe. Available in matte black with gold foil or white with copper foil. Makes every morning special.",
    price: 599,
    basePrice: 999,
    discount: 40,
    rating: 4.5,
    reviews: 5612,
    image: "/products/mug.png",
    images: ["/products/mug.png"],
    ar: false,
    badge: "Based on wishlist",
    stock: 120,
    sku: "GG-004-PERS-MUG",
    colors: [
      { name: "Matte Black", hex: "#1F2937" },
      { name: "Pure White", hex: "#FFFFFF" },
      { name: "Navy Blue", hex: "#1E3A5F" },
    ],
    sizes: ["330ml", "450ml"],
    tags: ["personalized", "birthday", "corporate", "daily-use"],
    specifications: {
      Material: "Premium Ceramic",
      Capacity: "330ml / 450ml",
      Finish: "Gold / Copper Foil",
      Safety: "Microwave & Dishwasher Safe",
      Personalization: "Up to 30 characters",
    },
    careInstructions: "Dishwasher safe. Avoid abrasive scrubbers on printed area.",
  },
  {
    id: "gg-005",
    name: "Gold Filigree Bracelet",
    slug: "gold-filigree-bracelet",
    category: "Jewellery",
    categorySlug: "jewellery",
    brand: "Aurelia Fine Jewels",
    description:
      "18K gold-plated bracelet featuring traditional Indian filigree work from Cuttack, Odisha. Adjustable clasp fits all wrist sizes. Comes with a BIS hallmark certificate and luxury packaging.",
    price: 4999,
    basePrice: 6999,
    discount: 29,
    rating: 4.7,
    reviews: 891,
    image: "/products/bracelet.png",
    images: ["/products/bracelet.png"],
    ar: true,
    badge: "Premium Pick",
    stock: 8,
    sku: "GG-005-GOLD-BRC",
    colors: [
      { name: "Yellow Gold", hex: "#FFD700" },
      { name: "Rose Gold", hex: "#B76E79" },
      { name: "White Gold", hex: "#E8E8E8" },
    ],
    sizes: ["Adjustable"],
    tags: ["jewellery", "wedding", "anniversary", "diwali", "premium"],
    specifications: {
      Material: "18K Gold Plated Brass",
      Weight: "18g",
      Closure: "Adjustable Lobster Clasp",
      Certification: "BIS Hallmark",
      Origin: "Cuttack, Odisha",
    },
    careInstructions: "Store in anti-tarnish pouch. Avoid perfume and water contact. Polish with jewellery cloth.",
  },
  {
    id: "gg-006",
    name: "Wireless Speaker Pro",
    slug: "wireless-speaker-pro",
    category: "Electronics",
    categorySlug: "electronics",
    brand: "SoundCraft",
    description:
      "360° spatial audio speaker with deep bass and crystal-clear treble. IPX7 waterproof, 24-hour battery, and multi-device pairing. Premium fabric finish available in 3 colours.",
    price: 3299,
    basePrice: 4999,
    discount: 34,
    rating: 4.4,
    reviews: 2156,
    image: "/products/speaker.png",
    images: ["/products/speaker.png"],
    ar: false,
    badge: "Tech Lover's Choice",
    stock: 25,
    sku: "GG-006-SPKR-PRO",
    colors: [
      { name: "Charcoal", hex: "#374151" },
      { name: "Midnight Blue", hex: "#1E3A5F" },
      { name: "Sage Green", hex: "#6B8F71" },
    ],
    sizes: ["Standard"],
    tags: ["electronics", "birthday", "corporate", "tech"],
    specifications: {
      Driver: "52mm Full Range",
      Battery: "6000mAh (24 hours)",
      Connectivity: "Bluetooth 5.3, AUX, USB-C",
      Waterproof: "IPX7",
      Weight: "680g",
    },
    careInstructions: "Wipe with damp cloth. Charge fully before first use.",
  },
  {
    id: "gg-007",
    name: "Kashmiri Pashmina Scarf",
    slug: "kashmiri-pashmina-scarf",
    category: "Fashion",
    categorySlug: "fashion",
    brand: "Kashmir Looms",
    description:
      "Authentic GI-tagged Kashmiri Pashmina hand-woven by master artisans. 100% pure pashmina wool with traditional Sozni embroidery. Each piece takes 3-6 months to complete. A timeless luxury gift.",
    price: 3799,
    basePrice: 5499,
    discount: 31,
    rating: 4.8,
    reviews: 672,
    image: "/products/scarf.png",
    images: ["/products/scarf.png"],
    ar: false,
    badge: "Handcrafted",
    stock: 6,
    sku: "GG-007-PSHM-SCF",
    colors: [
      { name: "Ivory", hex: "#FFFFF0" },
      { name: "Burgundy", hex: "#800020" },
      { name: "Midnight Blue", hex: "#191970" },
    ],
    sizes: ["Standard (200×80cm)"],
    tags: ["fashion", "luxury", "wedding", "anniversary", "handcrafted"],
    specifications: {
      Material: "100% Pure Pashmina Wool",
      Dimensions: "200×80 cm",
      Embroidery: "Sozni (Hand)",
      Certification: "GI Tagged",
      Origin: "Srinagar, Kashmir",
    },
    careInstructions: "Dry clean only. Store flat in breathable bag. Avoid direct sunlight.",
  },
  {
    id: "gg-008",
    name: "Artisan Candle Collection",
    slug: "artisan-candle-collection",
    category: "Wellness",
    categorySlug: "wellness",
    brand: "Flicker & Co.",
    description:
      "Set of 4 hand-poured soy wax candles in premium glass vessels. Scents: Indian Sandalwood, Darjeeling Tea, Bombay Rose, and Himalayan Cedar. 40-hour burn time each. Perfect for Diwali or housewarming.",
    price: 1299,
    basePrice: 1999,
    discount: 35,
    rating: 4.6,
    reviews: 1834,
    image: "/products/candles.png",
    images: ["/products/candles.png"],
    ar: true,
    badge: "Gift Set",
    stock: 30,
    sku: "GG-008-CNDL-SET",
    colors: [
      { name: "Warm Amber", hex: "#D97706" },
      { name: "Cool Sage", hex: "#6B8F71" },
    ],
    sizes: ["Set of 4"],
    tags: ["wellness", "diwali", "housewarming", "birthday", "candles"],
    specifications: {
      Material: "100% Soy Wax",
      Scents: "Sandalwood, Tea, Rose, Cedar",
      "Burn Time": "40 hours each",
      Weight: "200g each",
      Vessel: "Reusable Glass",
    },
    careInstructions: "Trim wick to 5mm before each use. Burn for max 4 hours at a time.",
  },
];

export function getProduct(idOrSlug: string): Product | undefined {
  return products.find((p) => p.id === idOrSlug || p.slug === idOrSlug);
}

export function getProductsByCategory(slug: string): Product[] {
  return products.filter((p) => p.categorySlug === slug);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q)) ||
      p.description.toLowerCase().includes(q)
  );
}

// ── Demo Orders ──
export const demoOrders: Order[] = [
  {
    id: "GG-2026-7842",
    items: [
      {
        productId: "gg-001",
        quantity: 1,
        color: "Silver",
        size: "8×10",
        giftWrap: true,
        giftMessage: "Happy Anniversary! With love, always. 💝",
        product: products[0],
      },
    ],
    subtotal: 2499,
    discount: 500,
    gst: 360,
    shipping: 0,
    total: 2359,
    status: "shipped",
    paymentId: "pay_QxR4abc123def",
    paymentMethod: "UPI",
    address: {
      name: "Priya Sharma",
      phone: "+91 98765 43210",
      line1: "Flat 402, Celestia Towers",
      line2: "Andheri West",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400053",
    },
    timeline: [
      { status: "pending", label: "Order Placed", description: "Your order has been placed successfully", timestamp: "2026-04-18T10:30:00Z", completed: true },
      { status: "confirmed", label: "Confirmed", description: "Payment verified via UPI (Razorpay)", timestamp: "2026-04-18T10:31:00Z", location: "Payment Gateway", completed: true },
      { status: "processing", label: "Processing", description: "Gift wrapping & quality check in progress", timestamp: "2026-04-18T14:00:00Z", location: "GiftGenius Warehouse, Mumbai", completed: true },
      { status: "shipped", label: "Shipped", description: "Package picked up by Delhivery", timestamp: "2026-04-19T09:15:00Z", location: "Bhiwandi Hub, Maharashtra", completed: true },
      { status: "out_for_delivery", label: "Out for Delivery", description: "Your package is on its way!", timestamp: "", completed: false },
      { status: "delivered", label: "Delivered", description: "Package delivered successfully", timestamp: "", completed: false },
    ],
    createdAt: "2026-04-18T10:30:00Z",
    estimatedDelivery: "2026-04-22",
  },
];

export function getOrder(id: string): Order | undefined {
  return demoOrders.find((o) => o.id === id);
}
